//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBContext : DbContext
    {
        public DBContext()
            : base("name=DBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DMTinTuc> DMTinTuc { get; set; }
        public virtual DbSet<TinTuc> TinTuc { get; set; }
    
        public virtual int sp_GanRandomDMTinTuc_SetBased(Nullable<int> startId, Nullable<int> endId)
        {
            var startIdParameter = startId.HasValue ?
                new ObjectParameter("StartId", startId) :
                new ObjectParameter("StartId", typeof(int));
    
            var endIdParameter = endId.HasValue ?
                new ObjectParameter("EndId", endId) :
                new ObjectParameter("EndId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GanRandomDMTinTuc_SetBased", startIdParameter, endIdParameter);
        }
    
        public virtual int sp_InsertFakeTinTuc(Nullable<int> soLuong)
        {
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertFakeTinTuc", soLuongParameter);
        }
    
        public virtual int sp_TaoDMDaCap(Nullable<int> soCap, Nullable<int> soLuongMoiCap)
        {
            var soCapParameter = soCap.HasValue ?
                new ObjectParameter("SoCap", soCap) :
                new ObjectParameter("SoCap", typeof(int));
    
            var soLuongMoiCapParameter = soLuongMoiCap.HasValue ?
                new ObjectParameter("SoLuongMoiCap", soLuongMoiCap) :
                new ObjectParameter("SoLuongMoiCap", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoDMDaCap", soCapParameter, soLuongMoiCapParameter);
        }
    }
}
