//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMTinTuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DMTinTuc()
        {
            this.TinTuc = new HashSet<TinTuc>();
        }
    
        public int Id { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Cap { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> IdCap1 { get; set; }
        public Nullable<int> IdCap2 { get; set; }
        public Nullable<int> IdCap3 { get; set; }
        public Nullable<int> IdCap4 { get; set; }
        public Nullable<int> IdCap5 { get; set; }
        public Nullable<int> IdCap6 { get; set; }
        public Nullable<int> IdCap7 { get; set; }
        public int SoLuongTinTuc { get; set; } = 0;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuc> TinTuc { get; set; }
    }
}
