//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TinTuc()
        {
            this.DMTinTuc = new HashSet<DMTinTuc>();
        }
    
        public int Id { get; set; }
        public string TieuDe { get; set; }
        public string TrichNgan { get; set; }
        public string ChiTiet { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DMTinTuc> DMTinTuc { get; set; }
    }
}
